### ISSUE TITLE
ipconfig missing in bfb for ubuntu 22.04 install enviorement

### ISSUE THREAD

**Issue by pawel-baldysiak-dell** [Mellanox/bfb-build#11]
Recently I tested booting BFB bits over HTTP. To configure network I used 'bfnet=' kernel param.
It turns out that dump-initramfs-v0 for ubuntu 22.04 image is missing ipconfig - so bfpxe script from bfscripts is unable to configure network. I checked BFB from 23.09 release - and ipconfig is there, so it seems to be regression.

**Comment by vladsokolovsky** [comment]
Hello Pawel,
Do you mean "ifconfig"?

Regards,
Vladimir

**Comment by vladsokolovsky** [comment]
I added the following change to address this issue: https://github.com/Mellanox/bfb-build/commit/d501df5926bbb8d5db87ff03852096fc0376dca1

**Comment by pawel-baldysiak-dell** [comment]
Yes... It should be ifconfig :)
I tested your patch - it is solved now.
Thanks!
